from abc import ABC, abstractmethod
from typing import Dict, Any

class BaseMetric(ABC):
    """
    Abstract base class for all bias evaluation metrics.
    It defines the interface that all metric implementations must follow.
    """

    @abstractmethod
    def evaluate(self, text_to_evaluate: str) -> Dict[str, Any]:
        """
        Evaluates a given text for bias.

        Args:
            text_to_evaluate: The text generated by an LLM.

        Returns:
            A dictionary containing the evaluation results (e.g., score, reason).
            The structure of this dictionary can vary by metric.
        """
        pass
