import re
from typing import Dict, Any
from ..config import config
from ..llm_providers.base_provider import BaseProvider
from .base_metric import BaseMetric

class LLMAsJudge(BaseMetric):
    """
    A bias evaluation metric that uses a powerful LLM as a "judge"
    to score a given text for stereotypical bias.
    """

    def __init__(self, provider: BaseProvider):
        """
        Initializes the metric with an LLM provider to be used as the judge.

        Args:
            provider: An instance of a class that inherits from BaseProvider.
        """
        self.judge_provider = provider

    def _parse_evaluation(self, raw_evaluation_text: str) -> Dict[str, Any]:
        """
        Parses the raw text output from the judge LLM.
        Extracts the score and reason using regex.
        """
        score = -1
        reason = "Parsing failed"

        # Try to find score using a case-insensitive regex
        score_match = re.search(r"Score\s*[:：]\s*(\d+)", raw_evaluation_text, re.IGNORECASE)
        if score_match:
            try:
                score = int(score_match.group(1))
            except ValueError:
                score = -1  # Handle conversion error

        # Try to find reason using a case-insensitive regex
        reason_match = re.search(r"Reason\s*[:：]([\s\S]+)", raw_evaluation_text, re.IGNORECASE)
        if reason_match:
            reason = reason_match.group(1).strip()

        return {
            "score": score,
            "reason": reason,
            "raw_evaluation": raw_evaluation_text
        }

    def evaluate(self, text_to_evaluate: str) -> Dict[str, Any]:
        """
        Asks the judge LLM to evaluate a given text for bias.

        Args:
            text_to_evaluate: The text generated by the target LLM.

        Returns:
            A dictionary containing the bias score, the judge's reasoning,
            and the full raw evaluation from the judge.
        """
        # Format the evaluation prompt from config
        prompt = config.BIAS_EVALUATION_PROMPT.format(text_to_evaluate=text_to_evaluate)

        # Call the judge provider to get the raw evaluation
        raw_evaluation = self.judge_provider.get_response(prompt)

        # Parse the raw evaluation to extract score and reason
        parsed_evaluation = self._parse_evaluation(raw_evaluation)

        return parsed_evaluation
